function [g, g2, data]=qs_globals()

% global variables

g=struct(   'QS_EXIT',0,...
            'QS_RUNNING',0,...
            'QS_AQI',0,...
            'QS_TRIG_SIGNAL',0,...
            'QS_TRIG_TYPE',0,...
            'QS_TSCALE',0,...
            'QS_TRIG_LEVEL',0,...
            'QS_TLEVEL',0,...
            'QS_TRIG_PREROLL',0,...
            'QS_TRIG_RELFREQ',0,...
            'QS_TPREROLL',0,...
            'QS_TRELFREQ',0,...
            'QS_TRIGGER',0,...
            'QS_NSAMP',0,...
            'QS_NDOWN',0,...
            'QS_MEAS_RATE',0,...
            'QS_MSAMPRATE',0,...
            'QS_MEAS_LEN',0,...
            'QS_MFRAMELEN',0,...
            'QS_MEAS_NUM',0,...
            'QS_MNUMFRAMES',0,...
            'QS_IFRAME',0,...
            'QS_MEAS_TIME',0,...
            'QS_WINDOW',0,...
            'QS_AACONFIG',0,...
            'QS_SCOPE_ID',0,...
            'QS_SCOPE_CHAN',0,...
            'QS_SCOPE_HDL',0,...
            'QS_SCOPE_TYPE',0,...
            'QS_SCOPE_SCALE',0,...
            'QS_SCOPE_FREEZE',0,...
            'QS_SCOPE_DOFRF',0,...
            'QS_SCOPE_MEM',0,...
            'QS_SCOPE_MEM_XDAT',0,...
            'QS_SCOPE_MEM_YDAT',0,...
            'QS_SCOPE_MEM_IDAT',0,...
            'QS_SCOPE_MEM_LDAT',0,...
            'QS_SCOPE_XBAK',0,...
            'QS_COLOR',0,...
            'QS_CLIPPED',0,...
            'QS_COLOR_YELLOW',0,...
            'QS_COLOR_GREY',0,...
            'QS_COLOR_GREEN',0,...
            'QS_COLOR_RED',0,...
            'QS_CHAN_SIGNAL',0,...
            'QS_MAXSCOPE',0,...
            'QS_MAXCHAN',0,...
            'QS_MAXFRAME',0,...
            'QS_ICHOICE',0,...
            'QS_LAST_CHOICES',0,...
            'QS_IN',0,...
            'QS_OUT',0,...
            'QS_AVG_ON',0,...
            'QS_REDRAW',0,...
            'QS_FIRSTRUN',0,...
            'QS_VALID',0,...
            'QSG_GEN_SIGNAL',0,...
            'QSG_GEN_CHAN',0,...
            'QSG_GEN_OPEN',0,...
            'QSG_GEN_FREQ_SELECT',1,...
            'QSG_GEN_AMP_SELECT',1,...
	    'QSG_FIG',0,...
            'QS_MAXLEV',0,...
            'QS_MAXFREQ',0,...
            'QS_NRATES',0,...
	    'QS_IS_SIMULINK',0,...
	    'QS_GATE_ERROR',0,...
	    'QS_GUI_OPEN',0,...
	    'QS_NDEVS',0,...
	    'QS_CHAN_IN_STATE',0,...
	    'QS_CHAN_IN_OFFSET',0,...       %
	    'QS_CHAN_IN_RANGE',0,...        %range ddown menu index
	    'QS_CHAN_OUT_STATE',0,...       %
	    'QS_CHAN_OUT_OFFSET',0,...      %
	    'QS_CURRENT_DEVICE',0);

g2=struct('QS_HANDLES',0,...
	  'QS_FIG',0,...
	  'QS_SCOPE_HDLS',0);
	    
data=struct('TIM_XT',0,...
            'XT',0,...
            'FREQ_XF',0,...
            'XF_MOD',0,...
            'XF_PHS',0,...
            'FREQ_PSD_AUTO',0,...
            'PSD_AUTO',0,...
            'FREQ_FRF',0,...
            'FRF_MOD',0,...
            'FRF_PHS',0,...
            'PSD_CROSS',0,...
            'COH',0);
